import { CSSProperties } from 'react';

export const InlineStyle = () => {
  const divStyle = {
    color: 'red',
    fontSize: '17px',
    border: '1px solid black',
    width: 'fit-content',
    padding: '10px',
  } as CSSProperties;

  return <div style={divStyle}>Hello World</div>;
};

// const CSSProperties: {
//   accentColor: AccentColor | undefined;
//   alignContent: AlignContent | undefined;
//   alignItems: AlignItems | undefined;
//   alignSelf: AlignSelf | undefined;
//   alignTracks: AlignTracks | undefined;
//   animationComposition: AnimationComposition | undefined;
//   animationDelay: AnimationDelay<string & {}> | undefined;
//   animationDirection: AnimationDirection | undefined;
//   animationDuration: AnimationDuration<string & {}> | undefined;
//   animationFillMode: AnimationFillMode | undefined;
//   animationIterationCount: AnimationIterationCount | undefined;
//   animationName: AnimationName | undefined;
//   animationPlayState: AnimationPlayState | undefined;
//   animationRangeEnd: AnimationRangeEnd<string | number> | undefined;
//   animationRangeStart: AnimationRangeStart<string | number> | undefined;
//   animationTimeline: AnimationTimeline | undefined;
//   animationTimingFunction: AnimationTimingFunction | undefined;
//   appearance: Appearance | undefined;
//   aspectRatio: AspectRatio | undefined;
//   backdropFilter: BackdropFilter | undefined;
//   backfaceVisibility: BackfaceVisibility | undefined;
//   backgroundAttachment: BackgroundAttachment | undefined;
//   backgroundBlendMode: BackgroundBlendMode | undefined;
//   backgroundClip: BackgroundClip | undefined;
//   backgroundColor: BackgroundColor | undefined;
//   backgroundImage: BackgroundImage | undefined;
//   backgroundOrigin: BackgroundOrigin | undefined;
//   backgroundPositionX: BackgroundPositionX<string | number> | undefined;
//   backgroundPositionY: BackgroundPositionY<string | number> | undefined;
//   backgroundRepeat: BackgroundRepeat | undefined;
//   backgroundSize: BackgroundSize<string | number> | undefined;
//   blockOverflow: BlockOverflow | undefined;
//   blockSize: BlockSize<string | number> | undefined;
//   borderBlockColor: BorderBlockColor | undefined;
//   borderBlockEndColor: BorderBlockEndColor | undefined;
//   borderBlockEndStyle: BorderBlockEndStyle | undefined;
//   borderBlockEndWidth: BorderBlockEndWidth<string | number> | undefined;
//   borderBlockStartColor: BorderBlockStartColor | undefined;
//   borderBlockStartStyle: BorderBlockStartStyle | undefined;
//   borderBlockStartWidth: BorderBlockStartWidth<string | number> | undefined;
//   borderBlockStyle: BorderBlockStyle | undefined;
//   borderBlockWidth: BorderBlockWidth<string | number> | undefined;
//   borderBottomColor: BorderBottomColor | undefined;
//   borderBottomLeftRadius: BorderBottomLeftRadius<string | number> | undefined;
//   borderBottomRightRadius: BorderBottomRightRadius<string | number> | undefined;
//   borderBottomStyle: BorderBottomStyle | undefined;
//   borderBottomWidth: BorderBottomWidth<string | number> | undefined;
//   borderCollapse: BorderCollapse | undefined;
//   borderEndEndRadius: BorderEndEndRadius<string | number> | undefined;
//   borderEndStartRadius: BorderEndStartRadius<string | number> | undefined;
//   borderImageOutset: BorderImageOutset<string | number> | undefined;
//   borderImageRepeat: BorderImageRepeat | undefined;
//   borderImageSlice: BorderImageSlice | undefined;
//   borderImageSource: BorderImageSource | undefined;
//   borderImageWidth: BorderImageWidth<string | number> | undefined;
//   borderInlineColor: BorderInlineColor | undefined;
//   borderInlineEndColor: BorderInlineEndColor | undefined;
//   borderInlineEndStyle: BorderInlineEndStyle | undefined;
//   borderInlineEndWidth: BorderInlineEndWidth<string | number> | undefined;
//   borderInlineStartColor: BorderInlineStartColor | undefined;
//   borderInlineStartStyle: BorderInlineStartStyle | undefined;
//   borderInlineStartWidth: BorderInlineStartWidth<string | number> | undefined;
//   borderInlineStyle: BorderInlineStyle | undefined;
//   borderInlineWidth: BorderInlineWidth<string | number> | undefined;
//   borderLeftColor: BorderLeftColor | undefined;
//   borderLeftStyle: BorderLeftStyle | undefined;
//   borderLeftWidth: BorderLeftWidth<string | number> | undefined;
//   borderRightColor: BorderRightColor | undefined;
//   borderRightStyle: BorderRightStyle | undefined;
//   borderRightWidth: BorderRightWidth<string | number> | undefined;
//   borderSpacing: BorderSpacing<string | number> | undefined;
//   borderStartEndRadius: BorderStartEndRadius<string | number> | undefined;
//   borderStartStartRadius: BorderStartStartRadius<string | number> | undefined;
//   borderTopColor: BorderTopColor | undefined;
//   borderTopLeftRadius: BorderTopLeftRadius<string | number> | undefined;
//   borderTopRightRadius: BorderTopRightRadius<string | number> | undefined;
//   borderTopStyle: BorderTopStyle | undefined;
//   borderTopWidth: BorderTopWidth<string | number> | undefined;
//   bottom: Bottom<string | number> | undefined;
//   boxDecorationBreak: BoxDecorationBreak | undefined;
//   boxShadow: BoxShadow | undefined;
//   boxSizing: BoxSizing | undefined;
//   breakAfter: BreakAfter | undefined;
//   breakBefore: BreakBefore | undefined;
//   breakInside: BreakInside | undefined;
//   captionSide: CaptionSide | undefined;
//   caretColor: CaretColor | undefined;
//   caretShape: CaretShape | undefined;
//   clear: Clear | undefined;
//   clipPath: ClipPath | undefined;
//   color: Color | undefined;
//   colorAdjust: PrintColorAdjust | undefined;
//   colorScheme: ColorScheme | undefined;
//   columnCount: ColumnCount | undefined;
//   columnFill: ColumnFill | undefined;
//   columnGap: ColumnGap<string | number> | undefined;
//   columnRuleColor: ColumnRuleColor | undefined;
//   columnRuleStyle: ColumnRuleStyle | undefined;
//   columnRuleWidth: ColumnRuleWidth<string | number> | undefined;
//   columnSpan: ColumnSpan | undefined;
//   columnWidth: ColumnWidth<string | number> | undefined;
//   contain: Contain | undefined;
//   containIntrinsicBlockSize: ContainIntrinsicBlockSize<string | number> | undefined;
//   containIntrinsicHeight: ContainIntrinsicHeight<string | number> | undefined;
//   containIntrinsicInlineSize: ContainIntrinsicInlineSize<string | number> | undefined;
//   containIntrinsicWidth: ContainIntrinsicWidth<string | number> | undefined;
//   containerName: ContainerName | undefined;
//   containerType: ContainerType | undefined;
//   content: Content | undefined;
//   contentVisibility: ContentVisibility | undefined;
//   counterIncrement: CounterIncrement | undefined;
//   counterReset: CounterReset | undefined;
//   counterSet: CounterSet | undefined;
//   cursor: Cursor | undefined;
//   direction: Direction | undefined;
//   display: Display | undefined;
//   emptyCells: EmptyCells | undefined;
//   filter: Filter | undefined;
//   flexBasis: FlexBasis<string | number> | undefined;
//   flexDirection: FlexDirection | undefined;
//   flexGrow: FlexGrow | undefined;
//   flexShrink: FlexShrink | undefined;
//   flexWrap: FlexWrap | undefined;
//   float: Float | undefined;
//   fontFamily: FontFamily | undefined;
//   fontFeatureSettings: FontFeatureSettings | undefined;
//   fontKerning: FontKerning | undefined;
//   fontLanguageOverride: FontLanguageOverride | undefined;
//   fontOpticalSizing: FontOpticalSizing | undefined;
//   fontPalette: FontPalette | undefined;
//   fontSize: FontSize<string | number> | undefined;
//   fontSizeAdjust: FontSizeAdjust | undefined;
//   fontSmooth: FontSmooth<string | number> | undefined;
//   fontStretch: FontStretch | undefined;
//   fontStyle: FontStyle | undefined;
//   fontSynthesis: FontSynthesis | undefined;
//   fontSynthesisPosition: FontSynthesisPosition | undefined;
//   fontSynthesisSmallCaps: FontSynthesisSmallCaps | undefined;
//   fontSynthesisStyle: FontSynthesisStyle | undefined;
//   fontSynthesisWeight: FontSynthesisWeight | undefined;
//   fontVariant: FontVariant | undefined;
//   fontVariantAlternates: FontVariantAlternates | undefined;
//   fontVariantCaps: FontVariantCaps | undefined;
//   fontVariantEastAsian: FontVariantEastAsian | undefined;
//   fontVariantEmoji: FontVariantEmoji | undefined;
//   fontVariantLigatures: FontVariantLigatures | undefined;
//   fontVariantNumeric: FontVariantNumeric | undefined;
//   fontVariantPosition: FontVariantPosition | undefined;
//   fontVariationSettings: FontVariationSettings | undefined;
//   fontWeight: FontWeight | undefined;
//   forcedColorAdjust: ForcedColorAdjust | undefined;
//   gridAutoColumns: GridAutoColumns<string | number> | undefined;
//   gridAutoFlow: GridAutoFlow | undefined;
//   gridAutoRows: GridAutoRows<string | number> | undefined;
//   gridColumnEnd: GridColumnEnd | undefined;
//   gridColumnStart: GridColumnStart | undefined;
//   gridRowEnd: GridRowEnd | undefined;
//   gridRowStart: GridRowStart | undefined;
//   gridTemplateAreas: GridTemplateAreas | undefined;
//   gridTemplateColumns: GridTemplateColumns<string | number> | undefined;
//   gridTemplateRows: GridTemplateRows<string | number> | undefined;
//   hangingPunctuation: HangingPunctuation | undefined;
//   height: Height<string | number> | undefined;
//   hyphenateCharacter: HyphenateCharacter | undefined;
//   hyphenateLimitChars: HyphenateLimitChars | undefined;
//   hyphens: Hyphens | undefined;
//   imageOrientation: ImageOrientation | undefined;
//   imageRendering: ImageRendering | undefined;
//   imageResolution: ImageResolution | undefined;
//   initialLetter: InitialLetter | undefined;
//   inlineSize: InlineSize<string | number> | undefined;
//   inputSecurity: InputSecurity | undefined;
//   insetBlockEnd: InsetBlockEnd<string | number> | undefined;
//   insetBlockStart: InsetBlockStart<string | number> | undefined;
//   insetInlineEnd: InsetInlineEnd<string | number> | undefined;
//   insetInlineStart: InsetInlineStart<string | number> | undefined;
//   isolation: Isolation | undefined;
//   justifyContent: JustifyContent | undefined;
//   justifyItems: JustifyItems | undefined;
//   justifySelf: JustifySelf | undefined;
//   justifyTracks: JustifyTracks | undefined;
//   left: Left<string | number> | undefined;
//   letterSpacing: LetterSpacing<string | number> | undefined;
//   lineBreak: LineBreak | undefined;
//   lineHeight: LineHeight<string | number> | undefined;
//   lineHeightStep: LineHeightStep<string | number> | undefined;
//   listStyleImage: ListStyleImage | undefined;
//   listStylePosition: ListStylePosition | undefined;
//   listStyleType: ListStyleType | undefined;
//   marginBlockEnd: MarginBlockEnd<string | number> | undefined;
//   marginBlockStart: MarginBlockStart<string | number> | undefined;
//   marginBottom: MarginBottom<string | number> | undefined;
//   marginInlineEnd: MarginInlineEnd<string | number> | undefined;
//   marginInlineStart: MarginInlineStart<string | number> | undefined;
//   marginLeft: MarginLeft<string | number> | undefined;
//   marginRight: MarginRight<string | number> | undefined;
//   marginTop: MarginTop<string | number> | undefined;
//   marginTrim: MarginTrim | undefined;
//   maskBorderMode: MaskBorderMode | undefined;
//   maskBorderOutset: MaskBorderOutset<string | number> | undefined;
//   maskBorderRepeat: MaskBorderRepeat | undefined;
//   maskBorderSlice: MaskBorderSlice | undefined;
//   maskBorderSource: MaskBorderSource | undefined;
//   maskBorderWidth: MaskBorderWidth<string | number> | undefined;
//   maskClip: MaskClip | undefined;
//   maskComposite: MaskComposite | undefined;
//   maskImage: MaskImage | undefined;
//   maskMode: MaskMode | undefined;
//   maskOrigin: MaskOrigin | undefined;
//   maskPosition: MaskPosition<string | number> | undefined;
//   maskRepeat: MaskRepeat | undefined;
//   maskSize: MaskSize<string | number> | undefined;
//   maskType: MaskType | undefined;
//   masonryAutoFlow: MasonryAutoFlow | undefined;
//   mathDepth: MathDepth | undefined;
//   mathShift: MathShift | undefined;
//   mathStyle: MathStyle | undefined;
//   maxBlockSize: MaxBlockSize<string | number> | undefined;
//   maxHeight: MaxHeight<string | number> | undefined;
//   maxInlineSize: MaxInlineSize<string | number> | undefined;
//   maxLines: MaxLines | undefined;
//   maxWidth: MaxWidth<string | number> | undefined;
//   minBlockSize: MinBlockSize<string | number> | undefined;
//   minHeight: MinHeight<string | number> | undefined;
//   minInlineSize: MinInlineSize<string | number> | undefined;
//   minWidth: MinWidth<string | number> | undefined;
//   mixBlendMode: MixBlendMode | undefined;
//   motionDistance: OffsetDistance<string | number> | undefined;
//   motionPath: OffsetPath | undefined;
//   motionRotation: OffsetRotate | undefined;
//   objectFit: ObjectFit | undefined;
//   objectPosition: ObjectPosition<string | number> | undefined;
//   offsetAnchor: OffsetAnchor<string | number> | undefined;
//   offsetDistance: OffsetDistance<string | number> | undefined;
//   offsetPath: OffsetPath | undefined;
//   offsetPosition: OffsetPosition<string | number> | undefined;
//   offsetRotate: OffsetRotate | undefined;
//   offsetRotation: OffsetRotate | undefined;
//   opacity: Opacity | undefined;
//   order: Order | undefined;
//   orphans: Orphans | undefined;
//   outlineColor: OutlineColor | undefined;
//   outlineOffset: OutlineOffset<string | number> | undefined;
//   outlineStyle: OutlineStyle | undefined;
//   outlineWidth: OutlineWidth<string | number> | undefined;
//   overflowAnchor: OverflowAnchor | undefined;
//   overflowBlock: OverflowBlock | undefined;
//   overflowClipBox: OverflowClipBox | undefined;
//   overflowClipMargin: OverflowClipMargin<string | number> | undefined;
//   overflowInline: OverflowInline | undefined;
//   overflowWrap: OverflowWrap | undefined;
//   overflowX: OverflowX | undefined;
//   overflowY: OverflowY | undefined;
//   overlay: Overlay | undefined;
//   overscrollBehaviorBlock: OverscrollBehaviorBlock | undefined;
//   overscrollBehaviorInline: OverscrollBehaviorInline | undefined;
//   overscrollBehaviorX: OverscrollBehaviorX | undefined;
//   overscrollBehaviorY: OverscrollBehaviorY | undefined;
//   paddingBlockEnd: PaddingBlockEnd<string | number> | undefined;
//   paddingBlockStart: PaddingBlockStart<string | number> | undefined;
//   paddingBottom: PaddingBottom<string | number> | undefined;
//   paddingInlineEnd: PaddingInlineEnd<string | number> | undefined;
//   paddingInlineStart: PaddingInlineStart<string | number> | undefined;
//   paddingLeft: PaddingLeft<string | number> | undefined;
//   paddingRight: PaddingRight<string | number> | undefined;
//   paddingTop: PaddingTop<string | number> | undefined;
//   page: Page | undefined;
//   pageBreakAfter: PageBreakAfter | undefined;
//   pageBreakBefore: PageBreakBefore | undefined;
//   pageBreakInside: PageBreakInside | undefined;
//   paintOrder: PaintOrder | undefined;
//   perspective: Perspective<string | number> | undefined;
//   perspectiveOrigin: PerspectiveOrigin<string | number> | undefined;
//   pointerEvents: PointerEvents | undefined;
//   position: Position | undefined;
//   printColorAdjust: PrintColorAdjust | undefined;
//   quotes: Quotes | undefined;
//   resize: Resize | undefined;
//   right: Right<string | number> | undefined;
//   rotate: Rotate | undefined;
//   rowGap: RowGap<string | number> | undefined;
//   rubyAlign: RubyAlign | undefined;
//   rubyMerge: RubyMerge | undefined;
//   rubyPosition: RubyPosition | undefined;
//   scale: Scale | undefined;
//   scrollBehavior: ScrollBehavior | undefined;
//   scrollMarginBlockEnd: ScrollMarginBlockEnd<string | number> | undefined;
//   scrollMarginBlockStart: ScrollMarginBlockStart<string | number> | undefined;
//   scrollMarginBottom: ScrollMarginBottom<string | number> | undefined;
//   scrollMarginInlineEnd: ScrollMarginInlineEnd<string | number> | undefined;
//   scrollMarginInlineStart: ScrollMarginInlineStart<string | number> | undefined;
//   scrollMarginLeft: ScrollMarginLeft<string | number> | undefined;
//   scrollMarginRight: ScrollMarginRight<string | number> | undefined;
//   scrollMarginTop: ScrollMarginTop<string | number> | undefined;
//   scrollPaddingBlockEnd: ScrollPaddingBlockEnd<string | number> | undefined;
//   scrollPaddingBlockStart: ScrollPaddingBlockStart<string | number> | undefined;
//   scrollPaddingBottom: ScrollPaddingBottom<string | number> | undefined;
//   scrollPaddingInlineEnd: ScrollPaddingInlineEnd<string | number> | undefined;
//   scrollPaddingInlineStart: ScrollPaddingInlineStart<string | number> | undefined;
//   scrollPaddingLeft: ScrollPaddingLeft<string | number> | undefined;
//   scrollPaddingRight: ScrollPaddingRight<string | number> | undefined;
//   scrollPaddingTop: ScrollPaddingTop<string | number> | undefined;
//   scrollSnapAlign: ScrollSnapAlign | undefined;
//   scrollSnapMarginBottom: ScrollMarginBottom<string | number> | undefined;
//   scrollSnapMarginLeft: ScrollMarginLeft<string | number> | undefined;
//   scrollSnapMarginRight: ScrollMarginRight<string | number> | undefined;
//   scrollSnapMarginTop: ScrollMarginTop<string | number> | undefined;
//   scrollSnapStop: ScrollSnapStop | undefined;
//   scrollSnapType: ScrollSnapType | undefined;
//   scrollTimelineAxis: ScrollTimelineAxis | undefined;
//   scrollTimelineName: ScrollTimelineName | undefined;
//   scrollbarColor: ScrollbarColor | undefined;
//   scrollbarGutter: ScrollbarGutter | undefined;
//   scrollbarWidth: ScrollbarWidth | undefined;
//   shapeImageThreshold: ShapeImageThreshold | undefined;
//   shapeMargin: ShapeMargin<string | number> | undefined;
//   shapeOutside: ShapeOutside | undefined;
//   tabSize: TabSize<string | number> | undefined;
//   tableLayout: TableLayout | undefined;
//   textAlign: TextAlign | undefined;
//   textAlignLast: TextAlignLast | undefined;
//   textCombineUpright: TextCombineUpright | undefined;
//   textDecorationColor: TextDecorationColor | undefined;
//   textDecorationLine: TextDecorationLine | undefined;
//   textDecorationSkip: TextDecorationSkip | undefined;
//   textDecorationSkipInk: TextDecorationSkipInk | undefined;
//   textDecorationStyle: TextDecorationStyle | undefined;
//   textDecorationThickness: TextDecorationThickness<string | number> | undefined;
//   textEmphasisColor: TextEmphasisColor | undefined;
//   textEmphasisPosition: TextEmphasisPosition | undefined;
//   textEmphasisStyle: TextEmphasisStyle | undefined;
//   textIndent: TextIndent<string | number> | undefined;
//   textJustify: TextJustify | undefined;
//   textOrientation: TextOrientation | undefined;
//   textOverflow: TextOverflow | undefined;
//   textRendering: TextRendering | undefined;
//   textShadow: TextShadow | undefined;
//   textSizeAdjust: TextSizeAdjust | undefined;
//   textTransform: TextTransform | undefined;
//   textUnderlineOffset: TextUnderlineOffset<string | number> | undefined;
//   textUnderlinePosition: TextUnderlinePosition | undefined;
//   textWrap: TextWrap | undefined;
//   timelineScope: TimelineScope | undefined;
//   top: Top<string | number> | undefined;
//   touchAction: TouchAction | undefined;
//   transform: Transform | undefined;
//   transformBox: TransformBox | undefined;
//   transformOrigin: TransformOrigin<string | number> | undefined;
//   transformStyle: TransformStyle | undefined;
//   transitionBehavior: TransitionBehavior | undefined;
//   transitionDelay: TransitionDelay<string & {}> | undefined;
//   transitionDuration: TransitionDuration<string & {}> | undefined;
//   transitionProperty: TransitionProperty | undefined;
//   transitionTimingFunction: TransitionTimingFunction | undefined;
//   translate: Translate<string | number> | undefined;
//   unicodeBidi: UnicodeBidi | undefined;
//   userSelect: UserSelect | undefined;
//   verticalAlign: VerticalAlign<string | number> | undefined;
//   viewTimelineAxis: ViewTimelineAxis | undefined;
//   viewTimelineInset: ViewTimelineInset<string | number> | undefined;
//   viewTimelineName: ViewTimelineName | undefined;
//   viewTransitionName: ViewTransitionName | undefined;
//   visibility: Visibility | undefined;
//   whiteSpace: WhiteSpace | undefined;
//   whiteSpaceCollapse: WhiteSpaceCollapse | undefined;
//   whiteSpaceTrim: WhiteSpaceTrim | undefined;
//   widows: Widows | undefined;
//   width: Width<string | number> | undefined;
//   willChange: WillChange | undefined;
//   wordBreak: WordBreak | undefined;
//   wordSpacing: WordSpacing<string | number> | undefine...
